variables:
  projectName: shoe-ShoppingCart
  version: 0.0.1-SNAPSHOT
  projectUser: shoeshop
  projectPath: /datas/$projectUser/
  server: lab-server

stages:
  - build
  - deploy
  - showlog

build:
  stage: build
  variables:
    GIT_STRATEGY: clone
  script:
    - mvn install -DskipTests=true
  tags:
    - $server
  only:
    - tags

deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  when: manual
  script:
    - |
      if [ "$GITLAB_USER_LOGIN" == "voduchieu1" ]; then
        sudo cp target/$projectName-$version.jar $projectPath
        sudo chown -R $projectUser. $projectPath
        sudo kill -9 $(ps -ef | grep $projectName-$version.jar | grep -v grep | awk '{print $2}') || true
        sudo su $projectUser -c "cd $projectPath; nohup java -jar     $projectName-$version.jar > nohup.out 2>&1 &"
      else
        echo "Permission Denied"
        exit 1
      fi
  tags:
    - $server
  only:
    - tags

showlog:
  stage: showlog
  variables:
    GIT_STRATEGY: none
  when: manual
  script:
    - sudo su $projectUser -c "cd $projectPath; tail -n 10000 nohup.out"
  tags:
    - $server
  only:
    - tags
